import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

/**
 * Geteilte Sidebar-Definition für alle Add-on-Instanzen.
 *
 * Jede Docs-Instanz baut ihre Seitenleiste automatisch aus der Ordnerstruktur
 * ihres eigenen docs-<id>/-Verzeichnisses auf. Die Reihenfolge steuert das
 * `sidebar_position`-Front-Matter bzw. `_category_.json` in Unterordnern.
 */
const sidebars: SidebarsConfig = {
  docs: [{type: 'autogenerated', dirName: '.'}],
};

export default sidebars;
